includes/criteria/CriterionIsNonNumeric.php
includes/criteria/CriterionMapLayer.php
includes/parserhooks/Maps_LayerDefinition.php
includes/parserhooks/Maps_MapsDoc.php

Imported from: https://gerrit.wikimedia.org/r/#/c/262160/1
Bug: T70750

Replace wfMsg* calls

---

Maps.php
composer.json
docs/INSTALL.md
docs/RELEASE-NOTES.md

3.4.1 release

---

Maps.resources.php
includes/ext.maps.services.js

To keep internals of a service hidden and only expose an interface so
that external users have access to it via the RL.
```
var service = new maps.services( $( this ) );
service.render( 'google' );
```
refs https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1404#issuecomment-180504474

Add ext.maps.services

---

includes/Maps_Mapper.php

This method has been deprecated since MediaWiki 1.21. It is recommended to use
Xml::encodeJsVar() or Xml::encodeJsCall() instead.

Replace deprecated Xml::escapeJsString()

---

includes/services/GoogleMaps3/jquery.googlemap.js
includes/services/Leaflet/jquery.leaflet.js
includes/services/OpenLayers/jquery.openlayers.js

add removeMarkers functions to leaflet and openlayers (googlemaps3 already has this function) as noted in #117.
This is required for https://github.com/SemanticMediaWiki/SemanticMaps/pull/52 to work with leaflet and openlayers.

add removeMarkers to leaflet and openlayers

---

includes/services/GoogleMaps3/Maps_GoogleMaps3.php
includes/services/GoogleMaps3/jquery.googlemap.js

fix #158
Not shown by default.
Usage:
| controls = type, rotate
or
| controls = pan, zoom, type, scale, streetview, rotate
Tested.

add rotateControl to googlemaps

---

includes/services/OpenLayers/jquery.openlayers.js

fix https://github.com/SemanticMediaWiki/SemanticMaps/issues/80
I lost one line here: https://github.com/JeroenDeDauw/Maps/commit/a973fd93733983d7df24be8aac2f1633c20f8ff3#diff-5eb28ae85199d14351aaa7df78f774e6L96

fix openlayers centre bug

---

SemanticMaps/src/SM_AreaValueDescription.php

Note: update min SMW to 2.1
@mwjames `ValueDescription` has a `@since 1.6` tag, which is kinda misleading. For all I know I moved it and forgot this. Just saying, if you move and leave that as is, it's not ideal.

Do not use SMW class alias

---

Maps.php
Maps_Settings.php
composer.json
includes/services/GoogleMaps3/GoogleMaps3.php
includes/services/Leaflet/Leaflet.php
includes/services/OpenLayers/OpenLayers.php
tests/bootstrap.php

This adds settings to disable Maps and to disable its SMW integration.
It also removes everything but global declarations from code immediately
executed, so should allow for inclusion of Maps via Composer even without
MediaWiki being loaded.

Reordered initialization code

---

src/SemanticMaps.php

Broken in the last patch release due to moving of SM init code and use of `__DIR__`
Fixes https://github.com/JeroenDeDauw/Maps/issues/292

Fixed JS paths for SM files

---

includes/geocoders/Maps_GoogleGeocoder.php

Address is double urlencoded:
first time in $urlArgs initialization
second time in wfArrayToCgi function
That breaks it for Unicode-encoded languages (specifically Russian)

Maps_GoogleGeocoder - address being double urlencoded

---

SemanticMaps/src/queryprinters/SM_QueryHandler.php

[inset "I have no idea what I am doing" meme here]
I think this fixes https://github.com/JeroenDeDauw/Maps/issues/248
There are still issues though...
This breaks:
```
{{#ask:
[[Category:Locations]]
|?Has coordinates
|?Has location type
|?Located in
|format=googlemaps
|template=Location Popup
|showtitle=off
}}
```
And if you remove showtitle, it works

Poke the parser in a slightly different way

---

Maps.php
includes/parserhooks/Maps_Geocode.php

I noticed a fatal error when we want to call the `geocode` parser function. You can see an example here : https://sandbox.semantic-mediawiki.org/wiki/Seattle

Fatal error when calling geocode parser function

---

includes/services/Leaflet/jquery.leaflet.js

This fixes #360. 
Because the marker object loads the Leaflet's default icon when no icon is provided, and because we must wait until the custom icon is loaded to know its size, I'm setting the opacity of the marker to 0. Otherwise, the default icon might appear subliminally.
For the position of the popup, I found that 2/3 of the icon's height looked nice. I'm also shifting the popup by 1px to the left when the width is odd. Those choices are of course quite arbitrary, so I'm open for suggestions ;)

Dynamically resize leaflet custom icons

---

Maps_Settings.php

Since `egMapsDefaultServices` defaults to the first service defined with `egMapsAvailableServices` if no service is enabled or an invalid service was provided by the user we should have a service here that is freely usable and does not require extra setup to be functional.

Re-arrange order of available mapping services

---

tests/Integration/parsers/DistanceParserTest.php
tests/Integration/parsers/WmsOverlayParserTest.php
tests/Unit/Elements/BaseElementTest.php
tests/bootstrap.php

Use the PHPUnit4And6Compat trait from MediaWiki core to make PHPUnit 4
methods work even when being run with PHPUnit 6. If it's being run with
an older MediaWiki core version, define a empty trait in the bootstrap
to avoid fatal errors. Since the lack of the trait means we're running
with PHPUnit 4, everything should work out.

Make tests compatible with PHPUnit 4 and 6

---

Maps.php

I couldn't find any use of egMapsStyleVersion, but to keep this commit simple,
I kept that variable and only removed the use of wgStyleVersion. Also, in case
something depends on its format I've substituted it with the number 1.
This way any use of it will still work and still invalidate cache if the Maps_VERSION
constant is changed.
Ref <https://phabricator.wikimedia.org/T181318>

Remove use of deprecated wgStyleVersion

---

includes/services/Leaflet/leaflet-providers/leaflet-providers.js

In leaflet-providers.js, layerOptions and global options are merged in a wrong order so that OSM attribution allways appear as the layer attribution whatever provider is used.
This PR simply inverts the options order. As a consequence, the right layer attribution appears on the map.

change providers options and global options order

---

Maps_Settings.php
includes/services/Leaflet/leaflet-providers/leaflet-providers.js

This PR adds the possibility to display French Geoportal Maps to Maps extension with leaflet provider.
Four maps types are added : 
- GeoportailFrance, 
- GeoportailFrance.orthos,
- GeoportailFrance.parcels,
- GeoportailFrance.ign_maps
Note that Geoportal Maps need an access key to be displayed. This PR uses a default public key that can be used as is but comes with no guarantee. 
Exemples : 
```
{{#display_map: 
|layer=GeoportailFrance
|service=leaflet
}}
```
```
{{#display_map: 
|layer=GeoportailFrance.orthos
|service=leaflet
}}
```
```
{{#display_map: 
|layer=GeoportailFrance.parcels
|service=leaflet
}}
```
```
{{#display_map: 
|layer=GeoportailFrance.ign_maps
|service=leaflet
}}
```

Adding some Geoportail France Maps

---

Maps.hooks.php
Maps_Settings.php
includes/services/Leaflet/jquery.leaflet.js

This PR adds the ability to configure apikeys for leaflet-providers layers into Maps_Settings.php
```
$GLOBALS['egMapsLeafletLayersApiKeys'] = [
'MapBox' => '',
'MapQuestOpen' => '',
'Thunderforest' => '<insert Thunderforest France API Key here>',
'GeoportailFrance' => '<insert Geoportail France API Key here>'
];
```
This works with providers that have an `apikey` option into their configurations objects into leaflet-providers. Eg. Thunderforest (not tested)  or GeoportailFrance (tested)

Adds some leaflet providers apikey configuration to Maps_Settings.php

---

RELEASE-NOTES.md
src/SemanticMW/ResultPrinters/KmlPrinter.php
src/SemanticMW/ResultPrinters/QueryHandler.php

This has been broken since at least 2013.
Not clear to me what the desired behavior is, and if anyone
cares about having it.

Remove pagelinktext param from KML format

---

src/DataAccess/MediaWikiFileUrlFinder.php

Previously MediaWikiFileUrlFinder was checking for the presence of "File:Something.png" page in the local wiki, but this page may be nonexistent for images that are in Wikimedia Commons, etc.
Proper way is to query RepoGroup::findFile() to find the file (it will find files from shared repositories too).

FileUrlFinder: fix marker images not being found in Shared repository

---

src/MapsHooks.php
src/MapsSetup.php

SkinTemplateNavigation was deprecated in 1.39.
SkinTemplateNavigation::Universal is available since 1.18

Deprecate SkinTemplateNavigation in favor of SkinTemplateNavigation::Universal

---

src/Map/CargoFormat/CargoFormat.php

Getting "Argument 1 passed to Maps\Map\CargoFormat\CargoFormat::__construct() must be an instance of ParserOutput, instance of OutputPage given, called in /srv/mediawiki/w/extensions/Cargo/includes/CargoQueryDisplayer.php on line 90"

Fix support for cargo

---

.github/workflows/ci.yml
src/GeoJsonPages/GeoJsonContent.php
src/GeoJsonPages/GeoJsonContentHandler.php
src/GeoJsonPages/GeoJsonLegacyContent.php
src/GeoJsonPages/GeoJsonMapPageUi.php
src/Presentation/OutputFacade.php

Move the HTML-setting into the ContentHandler instead of the Content.
Bug: #698

Remove deprecated method Content::fillParserOutput()

---

src/MapsRegistration.php

The extension can only be activated with wfLoadExtension which performs the required version check based on the data in extension.json, so there's no need for this additional check here.
This also refered to version "1.35c", which has never existed.

Remove MW version check from MapsRegistration

---

src/Map/CargoFormat/CargoFormat.php

```
Argument 2 passed to Maps\Map\CargoFormat\CargoFormat::__construct() must be an instance of ParserOutput, null given, called in /srv/mediawiki/w/extensions/Cargo/includes/CargoQueryDisplayer.php on line 90
```

Fix "must be an instance of ParserOutput, null given"

---

resources/GoogleMaps/jquery.googlemap.js
src/MapsHooks.php

Ensure all front-end asset paths use `egMapsScriptPath` as the base rather than building an asset path themselves. Derive `egMapsScriptPath` from the `ExtensionAssetsPath` config variable, since deployments may use this config var to customize the asset path for e.g. multi-version MediaWiki deployments.

Consistently use egMapsScriptPath for front-end asset paths

---

resources/leaflet/jquery.leaflet.js

Previously, leaflet maps would initially load and display *all* available base layers at once. This caused performance issues on clients with slow connections or limited memory.
The function that adds base layers to the map has been changed so that it only initially adds the last available base layer. This solves the problem while making sure the initially visible base layer stays the same (previously, although all base layers were loaded only the last layer was shown on top and was visible to the user).

FIX(leaflet): Load only one base layer at a time

---

.github/workflows/ci.yml
src/MapsHooks.php
src/MapsRegistration.php
src/MapsSetup.php
src/SemanticMapsSetup.php

PHP Deprecated:  Accessing $wgHooks directly is deprecated, use 
HookContainer::getHandlers() or HookContainer::register() instead
Bug: https://phabricator.wikimedia.org/T332687

Remove usage of wgHooks global variable

---

src/MapsHooks.php

This fixes the issue:
MediaWiki\Settings\SettingsBuilderException:
MediaWiki\Settings\SettingsBuilder::registerHookHandlers not supported in operation stage.
This is needed because the extension uses wgExtensionFunctions which does not appear to be working well with the SettingsBuilder
Bug: https://phabricator.wikimedia.org/T332687
Change-Id: I02c8a92ddc35cb55a488f5d9c8dbc41bc82b96a0

HookRunner: Use MediaWikiServices instance if available

---

src/GeoJsonPages/Semantic/SubObjectBuilder.php

This fixes the bug described in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5590 by assigning the caught exception to a variable in `SubObjectBuilder.php`.
This ensures compatibility with PHP versions 7.x as support for omitting the variable starts with 8.0.0.

fix: ensure catch syntax compatibility with PHP 7.x

---

src/SemanticMW/QueryHandler.php

It throws the error in MW 1.39.6 when you try to edit a page using VE with a map.
The error message:
```
Exception caught: Call to a member function getMaxIncludeSize() on null","errorclass":"Error","trace":
"Error at /var/www/mediawiki/w/includes/parser/Parser.php(2935)
from /var/www/mediawiki/w/includes/parser/Parser.php(2935)
#0 /var/www/mediawiki/w/includes/parser/Parser.php(1609): Parser->replaceVariables()
#1 /var/www/mediawiki/w/includes/parser/Parser.php(881): Parser->internalParse()
#2 /var/www/mediawiki/w/includes/parser/Parser.php(905): Parser->recursiveTagParse()
#3 /var/www/mediawiki/w/extensions/Maps/src/SemanticMW/QueryHandler.php(442): Parser->recursiveTagParseFully()
#4 /var/www/mediawiki/w/extensions/Maps/src/SemanticMW/QueryHandler.php(431): …
```

Fix for VusualEditor

---

src/SemanticMW/QueryHandler.php

The previous patch breaks widgets (and most likely other things) because it calls $parser->clearState() every time.

Do not call $parser->clearState() when parser options exist

---

tests/Integration/Semantic/AreaDescriptionTest.php

DB_MASTER was deprecated in MediaWiki 1.36 and removed in MediaWiki 1.43

Replace DB_MASTER with DB_PRIMARY
