- i18n/en.json
- i18n/qqq.json
Follow-up commits. Related to issue https://github.com/JeroenDeDauw/Maps/issues/60
> Add missing message "action-geocode"

- includes/services/GoogleMaps3/jquery.googlemap.js
As suggested by kvolden in https://github.com/JeroenDeDauw/Maps/issues/72
> Trigger map reseize on going fullscreen

- includes/services/GoogleMaps3/jquery.googlemap.js
> Changed styling of fullscreen button

- includes/services/OpenLayers/jquery.openlayers.js
@JeroenDeDauw 
I hope this fixes it.
> Fixed OpenLayers invalid style.css path with ResourceLoader enabled

- includes/services/OpenLayers/Maps_OpenLayers.php
- includes/services/OpenLayers/jquery.openlayers.js
Modified Maps_OpenLayers.php and jquery.openlayers.js to display KML data in OpenLayers map. --@akionux
> Displaying KML in OpenLayers map

- Maps.hooks.php
- Maps.php
- docs/RELEASE-NOTES.md
- i18n/en.json
* Add license lable to show on "Special:Version"
* Tweaked extension's description string to MW jargon
* File formatting
> Adding license lable and doing other tweaks

- Maps.resources.php
- includes/services/GoogleMaps3/GoogleMaps3.php
- includes/services/Leaflet/Leaflet.php
- includes/services/OpenLayers/OpenLayers.php
https://www.mediawiki.org/wiki/ResourceLoader/Writing_a_MobileFrontend_friendly_ResourceLoader_module#Enabling_your_existing_modules
> Add mobile target to resources

- composer.json
- tests/phpunit/parsers/DistanceParserTest.php
- tests/phpunit/parsers/LineParserTest.php
- tests/phpunit/parsers/LocationParserTest.php
- tests/phpunit/parsers/WmsOverlayParserTest.php
Fixes https://github.com/JeroenDeDauw/Maps/issues/128
> Fixed ValueParser tests to work with new version of DVC

- includes/services/OpenLayers/OSM/OpenStreetMap.js
Fixes #65, follow-up to https://github.com/JeroenDeDauw/Maps/pull/76
> Remove obsolete Osmarender layer code

- includes/Maps_Mapper.php
- tests/phpunit/MapsMapperTest.php
> Re-add icon=url

- Maps.php
- RELEASE-NOTES.md
Fixes https://github.com/JeroenDeDauw/Maps/issues/147
> 3.6.0 release

- includes/services/GoogleMaps3/jquery.googlemap.js
> make searchmarkers=all the default/fallback option

- includes/services/OpenLayers/jquery.openlayers.js
fix: https://github.com/SemanticMediaWiki/SemanticMaps/issues/46
> ol: show coords as lat-long

- includes/services/GoogleMaps3/gm3-util-library/README
- includes/services/GoogleMaps3/gm3-util-library/markerclusterer.js
from version 2.0.9
fix #159 
Tested.
> update googlemaps markerclustererplus to 2.1.2

- INSTALL.md
- Maps.php
- RELEASE-NOTES.md
Fixes https://github.com/JeroenDeDauw/Maps/issues/172
> 3.7.0 release

- Maps_Settings.php
- includes/geocoders/Maps_GoogleGeocoder.php
- includes/services/GoogleMaps3/Maps_GoogleMaps3.php
fixes #179
Haven't tested this yet.
> add GoogleMaps3 API key

- includes/services/OpenLayers/jquery.openlayers.js
See: https://github.com/JeroenDeDauw/Maps/blob/master/includes/services/OpenLayers/jquery.openlayers.js#L390 and https://github.com/JeroenDeDauw/Maps/blob/master/includes/services/OpenLayers/jquery.openlayers.js#L596
> OpenLayers: Remove duplicate resizable

- includes/services/GoogleMaps3/jquery.googlemap.js
remove markercluster when removing all markers.
> cleanup gm3 markercluster on removeMarkers

- Maps_Settings.php
- includes/geocoders/Maps_GoogleGeocoder.php
- includes/services/GoogleMaps3/Maps_GoogleMaps3.php
fix #181
Haven't tested this yet.
> add egMapsGMaps3ApiVersion number

- Maps_Settings.php
- includes/geocoders/Maps_GoogleGeocoder.php
- includes/services/GoogleMaps3/Maps_GoogleMaps3.php
see: https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
> remove gm3 sensor url parameter

- Maps.php
- Maps_Settings.php
- includes/geocoders/Maps_GoogleGeocoder.php
- includes/geocoders/Maps_NominatimGeocoder.php
- tests/phpunit/geocoders/NominatimGeocoderTest.php
> add nominatim geocoder

- includes/services/Leaflet/jquery.leaflet.js
see: https://github.com/JeroenDeDauw/Maps/pull/203#discussion_r73886596
Tested.
> leaflet: add getDependencies function

- includes/Geocoders.php
- includes/geocoders/Maps_OldGeocoderAdapter.php
- tests/phpunit/geocoders/MapsOldGeocoderAdapterTest.php
Since it most certainly is not a decorator...
> Corrected name of geocoding adapter

- composer.json
Part of https://github.com/JeroenDeDauw/Maps/issues/233
> Declare SMW compat and SM replacement in composer.json

- i18n/en.json
Fixes https://github.com/JeroenDeDauw/Maps/issues/178
> Add missing messages

- composer.json
Since apparently it prevents installation together with SMW dev-master
> Removed SMW compat upper bound from composer.json

- Maps.php
- RELEASE-NOTES.md
Fixes https://github.com/JeroenDeDauw/Maps/issues/250
> Added compat for old egGoogleJsApiKey setting

- Maps_Settings.php
Fixes https://github.com/JeroenDeDauw/Maps/issues/184
> Changed default mapping service to Leaflet

- Maps_Settings.php
- RELEASE-NOTES.md
@krabina relevant breaking change for you (easy to change back to old behaviour tho)
> Update release notes and disable tracking category

- Maps.php
- README.md
- RELEASE-NOTES.md
- SemanticMaps/src/SM_GeoCoordsValue.php
- includes/Geocoders.php
- includes/Maps_DisplayMapRenderer.php
- includes/parserhooks/Maps_DisplayMap.php
- includes/parsers/LocationParser.php
- tests/Integration/parserhooks/DisplayMapTest.php
It is now used for the main parameter. Still needs fixing for the
center parameter
> Mostly fixed the display_map geoservice parameter

- README.md
- SemanticMaps/src/queryprinters/SM_MapPrinter.php
- includes/Maps_DisplayMapRenderer.php
- includes/Maps_Mapper.php
- includes/Maps_MappingService.php
- includes/parserhooks/Maps_Coordinates.php
- includes/parserhooks/Maps_Finddestination.php
- includes/parserhooks/Maps_Geodistance.php
Another step towards fully fixing https://github.com/JeroenDeDauw/Maps/issues/285
> Fixed geoservice usage for center parameter in the map printer

- includes/Geocoders.php
As suggested by @aklapper in https://github.com/JeroenDeDauw/Maps/issues/298
Fixes https://github.com/JeroenDeDauw/Maps/issues/298
> Improved PHP 7 compatibility

- includes/parserhooks/Maps_MapsDoc.php
Fixes https://github.com/JeroenDeDauw/Validator/issues/18
> Fixed parameter type i18n in #mapsdoc

- SemanticMaps/src/queryprinters/SM_MapPrinter.php
Found this to be unused while hunting for a bug in it...
Presumably fixes https://github.com/JeroenDeDauw/Maps/issues/303
> Removed dead code

- src/Geocoders/NominatimGeocoder.php
- tests/Unit/Geocoders/NominatimGeocoderTest.php
Fixes https://github.com/JeroenDeDauw/Maps/issues/322
> Catch file fecthing errors in NominatimGeocoder

- includes/services/Leaflet/jquery.leaflet.js
> Fix leaflet marker custom icons (#304) and implement leaflet static map option (#351)

- includes/Geocoders.php
Fixes https://github.com/JeroenDeDauw/Maps/issues/366
> Use geocache setting again

- Maps.php
- Maps_Settings.php
- SemanticMaps/src/queryprinters/SM_MapPrinter.php
- includes/Maps_DisplayMapRenderer.php
- includes/parsers/CircleParser.php
- includes/parsers/ImageOverlayParser.php
- includes/parsers/LineParser.php
- includes/parsers/LocationParser.php
- includes/parsers/RectangleParser.php
- src/Geocoders/NullGeocoder.php
- src/Geocoders/StubGeocoder.php
- src/MapsFactory.php
- tests/Integration/parserhooks/FinddestinationTest.php
- tests/Integration/parsers/LocationParserTest.php
Fixes https://github.com/JeroenDeDauw/Maps/issues/365
> Stop using global state in LocationParser and LocationParserTest

- SemanticMaps/src/queryprinters/SM_QueryHandler.php
> Fully parse content of the popup window

- includes/services/Leaflet/Leaflet.php
As per PeterTheOne suggested at
https://github.com/JeroenDeDauw/Maps/issues/321#issuecomment-335158234
> Add missing Leaflet dependency specs

- INSTALL.md
- Maps.php
- RELEASE-NOTES.md
Fixes https://github.com/JeroenDeDauw/Maps/issues/376
> 5.0.0 release

- Maps.resources.php
- includes/services/GoogleMaps3/GoogleMaps3.php
- includes/services/Leaflet/Leaflet.php
- includes/services/OpenLayers/OpenLayers.php
changed path detection in problematic resource files.
> fixes #401; resource loading broken when maps not located directory named 'extensions'

- i18n/en.json
- includes/Maps_Mapper.php
- includes/services/Leaflet/Maps_Leaflet.php
- includes/services/Leaflet/jquery.leaflet.js
> Leaflet: Add parameter to disable mouse scrolling (fix #316)

- composer.json
Fixes https://github.com/JeroenDeDauw/Maps/issues/417
> Specify SimpleGeocoder version

- tests/Integration/parsers/DistanceParserTest.php
- tests/Integration/parsers/WmsOverlayParserTest.php
- tests/Unit/Elements/BaseElementTest.php
- tests/bootstrap.php
> Revert "Make tests compatible with PHPUnit 4 and 6"

- RELEASE-NOTES.md
- includes/parsers/ImageOverlayParser.php
- tests/Unit/Elements/ImageOverlayTest.php
Fixes https://github.com/JeroenDeDauw/Maps/issues/450
> Fix imageoverlays parameter

- Maps.php
- RELEASE-NOTES.md
- i18n/en.json
- i18n/qqq.json
- includes/services/Leaflet/Maps_Leaflet.php
- includes/services/Leaflet/jquery.leaflet.js
- src/MapsFactory.php
- src/Parsers/JsonFileParser.php
- tests/Integration/parsers/JsonFileParserTest.php
First step in https://github.com/JeroenDeDauw/Maps/issues/447
> Add basic GeoJson support for leaflet

- includes/ext.maps.common.js
- includes/ext.maps.coord.js
- includes/ext.maps.services.js
- includes/services/Leaflet/Leaflet.php
- includes/services/Leaflet/Maps_Leaflet.php
- includes/services/Leaflet/ext.maps.leaflet.js
- includes/services/Leaflet/leaflet.editable/Leaflet.Editable.js
- includes/services/Leaflet/leaflet.editor.js
- src/GeoJson/GeoJsonContent.php
- src/GeoJson/GeoJsonContentHandler.php
>  Add map view on GeoJson pages 

- extension.json
> Add missing load_composer_autoloader to extension.json

- i18n/en.json
Refs: https://github.com/JeroenDeDauw/Validator/issues/31 in a way
> Updates system messages

- RELEASE-NOTES.md
- extension.json
- includes/services/Leaflet/Maps_Leaflet.php
Fixes https://github.com/JeroenDeDauw/Maps/issues/477
> Fix weird resource loader issue

- MapsRegistration.php
- extension.json
This is needed to load the i18n if you use LocalisationCache ie rebuildLocalisationCache.php.
> Add missing i18n vars

- src/GoogleMapsService.php
Re-enable transit layer that are available along side with traffic and bicycling.
> Re-enable transit layer

- resources/GoogleMaps/geoxml3/geoxml3.js
Changed from neccessary  to necessary.
Bug: T201491
> Fixed typo "neccessary"

- resources/editor/js/mapeditor.js
Fixed Seperat to Separate 
T201491
> Fix typo "seperat"

- src/SemanticMW/ValueDescriptions/AreaDescription.php
- src/SemanticMW/ValueDescriptions/CoordinateDescription.php
Fixes https://github.com/JeroenDeDauw/Maps/issues/557
> Use IDatabase instead of DatabaseBase

- .travis.yml
As per https://github.com/JeroenDeDauw/Maps/pull/561#issuecomment-517880729
> Re-add MySql to TravisCI

- INSTALL.md
- extension.json
Fixes https://github.com/JeroenDeDauw/Maps/issues/578
> 7.9.0 release

- DefaultSettings.php
- RELEASE-NOTES.md
- resources/leaflet/jquery.leaflet.js
- src/MediaWiki/MapsHooks.php
Fixes https://github.com/JeroenDeDauw/Maps/issues/588
> Remove Leaflet dark layers

- .travis.yml
- tests/Integration/DataAccess/GeoJsonFetcherTest.php
- tests/Integration/DataAccess/MediaWikiFileUrlFinderTest.php
- tests/Integration/MapsDistanceParserTest.php
- tests/Integration/MapsMapperTest.php
- tests/Integration/MediaWiki/ParserHooks/ParserHookTest.php
- tests/Integration/Parser/DisplayMapTest.php
- tests/Integration/Semantic/ValueDescriptions/AreaDescriptionTest.php
- tests/Integration/parsers/LocationParserTest.php
- tests/System/SemanticMW/MapQueryTest.php
- tests/Unit/Semantic/DataValues/CoordinateValueTest.php
Cause stupid breaking changes...
> Add void return hints

- i18n/ar.json
- i18n/ast.json
- i18n/en.json
- i18n/fr.json
- i18n/gsw.json
- i18n/hr.json
- i18n/mk.json
- i18n/nb.json
- i18n/pl.json
- i18n/pt-br.json
- i18n/ru.json
- i18n/sv.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-hant.json
Add Special:MyLanguage to MediaWiki.org URLs for better user experience
> Add Special:MyLanguage for better user experience

- i18n/aliases/Aliases.php
This PR adds Polish special page alias for Special:MapEditor
> Add Polish special page alias

- DefaultSettings.php
- src/MapsFactory.php
Closes https://github.com/JeroenDeDauw/Maps/issues/644.
> New egMapsGeoCacheType setting

- .github/workflows/ci.yml
- INSTALL.md
- Makefile
- Maps_Settings.php
- README.md
- RELEASE-NOTES.md
- composer.json
- extension.json
- phpcs.xml
- src/MapsRegistration.php
- tests/Integration/InitializationTest.php
- tests/Integration/Parsers/DistanceParserTest.php
> Add info to MW autoloader

- resources/lib/leaflet-providers/leaflet-providers.js
> Add ÖPNV-Karte

- src/MapsFactory.php
- src/MapsSetup.php
> 720 add google geocoding api key

- .github/workflows/ci.yml
> CI: remove Composer allow-plugins

- src/LegacyMapEditor/SpecialMapEditor.php
> Update addModules to array format

- resources/lib/leaflet-providers/leaflet-providers.js
New URLs according to https://basemap.at/changelog/
> New URLs for Basemap.at

- extension.json
Fixes: #747
Bug: https://phabricator.wikimedia.org/T332837
> Load ext.maps.leaflet.editor on mobile

- extension.json
10.1 release, which also happens to be the 101th release of Maps :)
> 10.1 release

- INSTALL.md
> Tweak documentation

- src/Map/CargoFormat/CargoFormat.php
Fixes https://github.com/ProfessionalWiki/Maps/issues/781
> Add compat with latest Cargo versions

- i18n/en.json
https://github.com/ProfessionalWiki/Maps/pull/801#discussion_r1981495491
> Add missing validator-type-title message
